### ISSUE TITLE
Remove DefaultQueryParser and make Lucene fixed

### ISSUE THREAD

**Issue by coenm** [coenm/RepoM#109]

**Comment by coenm** [comment]
Currently:

```
Work:
  name: Work
  description: Work
  always-visible:
    kind: query@1
    query: is:pinned
  filter:
    kind: query@1
    query: '-tag:private AND (tag:work OR RepoM OR name:GitMonitor)'
```

**Comment by coenm** [comment]
```yaml
Work:
  name: Work
  description: Work
  always-visible:
    kind: query@1
    query: 
    - type: field-query@1
      name: is
      value: pinned 
  filter:
    kind: and-query@1
    parts:
    - kind: not-query@1
      query:
        kind: type: field-query@1
        name: tag
        value: private
....




```
