### ISSUE TITLE
Update autolabeler to match and categorize nbgv commits

### ISSUE THREAD

**Issue by coenm** [coenm/RepoM#141]
The nbgv command prepare-release creates a branch and a few commits. The dotnet-releaser tool can be configured to match and categorize these commits.

See [dotnet-releaser docs](https://github.com/xoofx/dotnet-releaser/blob/main/doc/changelog_user_guide.md#11-overview) for more info.

```toml

# Matches any title starting by e.g `Add/Improve/Fix/Update ci`
# and attach to the PR/Commit the `maintenance` label
[[changelog.autolabeler]]
label = "maintenance"
title = '^(([Aa]dd)|([Ii]mprove)|([Ff]ix)|([Uu]pdate))\s+ci\b'

```

The commits to match are:

![image](https://github.com/user-attachments/assets/4b0661cc-0073-45c8-8455-4c8a30f1f0c5)
