### ISSUE TITLE
Howto add context menu item 'Explore Remote Repository'?

### ISSUE THREAD

**Issue by gabriel-vanca** [coenm/RepoM#151]
Would be amazing of the old RepoZ menu option of opening the Github Repo in the browser would be brought back. It's the only thing that is stopping me from switching to RepoM.

**Comment by coenm** [comment]
No need to bring it back, it never left RepoM

[docs](https://github.com/coenm/RepoM/blob/main/docs_new/repom.generated.md#browse-repository1)

usage:

```yaml
- type: browse-repository@1
```

or for instance only when the repo is stored in GitHub

```yaml
context:
- type: evaluate-script@1
  content: |-

    func remotes_contain_inner(remotes, url_part)
      urls = remotes | array.map "url"
      filtered = array.filter(urls, do 
        ret string.contains($0, url_part) 
      end)
      ret array.size(filtered) > 0;
    end

    func remotes_contain(url_part)
      ret remotes_contain_inner(repository.remotes, url_part)
    end

    is_github_repository = remotes_contain("github.com");

action-menu:

- type: browse-repository@1
  active: "{{ is_github_repository }}" 
    
```

**Comment by coenm** [comment]
And if this menu item wasn't available. You could have created it youself using the following snippets:


```yaml

- type: just-text@1
  name: 'Warning: No remotes to browse to'
  active: array.size(repository.remotes) == 0

- type: url@1
  name: 'Browse to remote {{ repository.remotes[0].key }}'
  url: '{{ repository.remotes[0].url }}'
  active: array.size(repository.remotes) == 1

- type: folder@1
  name: Link to all remotes of repo
  active: array.size(repository.remotes) > 1
  actions:
  - type: foreach@1
    enumerable: repository.remotes
    variable: remote
    actions:
    - type: url@1
      name: 'Browse to remote {{ remote.key}}'
      url: '{{ remote.url }}'


```
