### ISSUE TITLE
Howto add a menu item to open the repository in Gitkraken

### ISSUE THREAD

**Issue by gabriel-vanca** [coenm/RepoM#163]
Please add open in GitKraken option.

**Comment by coenm** [comment]
RepoM is all about making your own context menu for your repositories.

In order to add an `Open in GitKraken` menu item you should:
1. Find the executable you want to open and take it's full path. I don't use GitKraken.
2. Check if GitKraken supports arguments to specify the repository you want to open using the directory of the repository.

When you have both, you can try it using a the windows terminal.
so for instance:

```
> cd C:\
> "C:\path\to\GitKraken\GitKraken.exe" -p "C:\path\to'repository\"
```
and see what happends. You can change and retry until you know what the desired command is.

The next step is to translate this into an RepoM action menu. This probably looks like:

```yaml

- type: executable@1
  name: Open in GitKraken
  executable: '{{ env.ProgramW6432 }}/Path/To/Gitkraken.exe.exe'
  arguments: -p "{{ repository.windows_path }}"

```

Note I'm not aware of all options of GitKraken. I used [this](https://stackoverflow.com/questions/53842400/how-can-i-start-gitkraken-from-the-command-line-with-a-git-repository-path-on-wi) link to learn about the `-p` option.

Repository variables to use in `RepositoryActionsV2.yaml` are listed [here](https://github.com/coenm/RepoM/blob/main/docs_new/script_variables_repository.generated.md) 

Also note that the `repository.windows_path` variable does NOT end with a slash so you might need to add an additional slash at the end if GitKraken requires this.

Let me know if you need help.
