### ISSUE TITLE
browse-repository@1 useless with forks

### ISSUE THREAD

**Issue by gabriel-vanca** [coenm/RepoM#170]
The `browse-repository@1` is broken when you're trying to navigate to a forked repo. It just shows the name of the repo twice, with no indication of which repo is the origin and which the upstream.

![image](https://github.com/user-attachments/assets/d06dbe2a-11b9-49ca-8e2c-542064841fcc)

By comparison, RepoZ used to show the links:

![image](https://github.com/user-attachments/assets/bc6e80e3-0bd2-468d-bcc9-7f32226ece0d)

As a temporary fix, I created a manual menu that shows the info more clear, but I think this should be default behaviour (ideally with an option to show/hide the `origin` and `upstream` bits)
Also a `repository.short_remotes` variable that only shows the `author\repo-name` would be ideal as I don't really need to know the full link.

```
- type: separator@1

- type: just-text@1
  name: 'Warning: No GitHub remotes to browse to'
  active: array.size(repository.remotes) == 0

# single remote, create url menu item
- type: url@1
  name: '🔗 GitHub remote repository' # {{ repository.remotes[0].key }}
  url: '{{ repository.remotes[0].url }}'
  active: array.size(repository.remotes) == 1

# Multiple remotes, create folder with multiple menu items
- type: folder@1
  name: 🔗 GitHub remote repositories
  active: array.size(repository.remotes) > 1
  actions:
  - type: foreach@1
    enumerable: repository.remotes
    variable: remote
    actions:
    - type: url@1
      name: '[{{ remote.key}}] {{ shorten_github_link(remote) }}'
      url: '{{ remote.url }}'

- type: separator@1
```

and the following function:

```
    func shorten_github_link(github_remote)
      ret github_remote.url | string.replace "https://github.com/" "" | string.replace ".git" "" | string.strip
    end
```

![image](https://github.com/user-attachments/assets/45d8de43-5b68-4fc4-9ac7-59ed56166c23)
