### ISSUE TITLE
Object variables

### ISSUE THREAD

**Issue by coenm** [coenm/RepoM#34]
```yml
variables:
- name: var1
  enabled: true
  value:
  - index: 1
    name: One
  - index: 2
    name: Two
```
