### ISSUE TITLE
for each in action provider

### ISSUE THREAD

**Issue by coenm** [coenm/RepoM#35]
Something like:

```yml

- type: foreach@1
  variable: currentItem
  array: {var.variablex}
  actions:
  - type: browser@1
    url: {var.currentItem}
```
